let
    Fonte = Consulta1(#date(2022, 1, 1), 1096, #duration(1, 0, 0, 0)),
    #"Convertido para Tabela" = Table.FromList(Fonte, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Coluna Renomeada" = Table.RenameColumns(#"Convertido para Tabela",{{"Column1", "Data"}}),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna Renomeada",{{"Data", type date}}),
    #"Dia Inserido" = Table.AddColumn(#"Tipo Alterado", "Dia", each Date.Day([Data]), Int64.Type),
    #"Mês Inserido" = Table.AddColumn(#"Dia Inserido", "Num Mês", each Date.Month([Data]), Int64.Type),
    #"Nome do Mês Inserido" = Table.AddColumn(#"Mês Inserido", "Nome do Mês", each Date.MonthName([Data]), type text),
    #"Mês abreviado" = Table.AddColumn(#"Nome do Mês Inserido", "Mês Abreviado", each Text.Start(Text.Proper([Nome do Mês]), 3), type text),
    #"Ano Inserido" = Table.AddColumn(#"Mês abreviado", "Ano", each Date.Year([Data]), Int64.Type)
in
    #"Ano Inserido"